name: ci-tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          ORGANIZATION_ACCESS_SSH_KEY: ${{ secrets.ORGANIZATION_ACCESS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          cat <<EOF > ~/.ssh/id_rsa
          $ORGANIZATION_ACCESS_SSH_KEY
          EOF
          cat <<EOT > ~/.ssh/config
          Host github.com
          User git
          Hostname github.com
          IdentityFile ~/.ssh/id_rsa
          AddKeysToAgent yes
          ForwardAgent yes
          EOT
          chmod -v 700 ~/.ssh/
          chmod -v 600 ~/.ssh/id_rsa

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
